# Generated by Django 4.2.1 on 2023-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='ayudante',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Ayudante', 'Ayudante')], default='Profesor', max_length=50),
        ),
    ]
