# Generated by Django 4.2.1 on 2023-06-23 22:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodel_ayudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
