# Generated by Django 4.2.1 on 2023-06-26 19:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postmodel_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
